spring:
  datasource:
    username: rzp-root
    password: rzp-root
    url: jdbc:mysql://127.0.0.1:3306/rzp-database?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  resources:
    static-locations: file:/srv/http/rzp/backend

media:
  upload:
    path: /srv/http/rzp/backend/static/media/

server:
  servlet:
    context-path: /rzp-blog
